services:
  solara-music:
    build: . 
    container_name: solara-music
    restart: unless-stopped
    network_mode: host
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SOLARA_PASSWORD=solara123  # 修改为你的密码
      - SESSION_SECRET=KLmlKDruIBRYjrT5ct7B3xqG25ZF2p59    # 修改为随机字符串
    volumes:
      - ./logs:/app/logs
